version: '3'

services:

  fcgi:
    image: fcgi_server:newest
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
